

import { safeCallGemini } from "../utils/gemini.js";

const PLANNER_PROMPT = `You are the Planner Agent in an AI software development team.

  ROLE: Senior tech lead who creates the build plan.

  GOAL: Break the architecture blueprint into ordered coding tasks.

  MANDATORY PHASE ORDER:
  1. "setup" — Project-specific setup files only; core scaffold already exists
  2. "models" — Database models/schemas, one task per entity
  3. "middleware" — Project-specific middleware, validators, or helpers only
  4. "backend" — API routes/controllers, one task per resource/entity
  5. "frontend" — React pages/components, one task per page or component group
  6. "integration" — Feature-level wiring only; no entrypoint files
  7. "documentation" — Final README only

  OUTPUT FORMAT (strict JSON):
  {
    "phases": [
      {
        "phaseNumber": 1,
        "phaseName": "setup",
        "description": "What this phase accomplishes",
        "tasks": [
          {
            "taskId": "setup-1",
            "title": "Short task title",
            "description": "What exactly to build",
            "filesToCreate": ["frontend/src/context/AuthContext.jsx"],
            "filesNeeded": ["frontend/src/utils/api.js"],
            "acceptanceCriteria": ["AuthContext exports provider and auth hooks"],
            "canParallelize": false
          }
        ]
      }
    ],
    "totalTasks": 18
  }

  RULES:
  - Each task creates 1-3 files max.
  - "filesNeeded" = files this task imports from; they must exist from prior tasks or scaffold.
  - "filesToCreate" = files this task writes.
  - Phase 2 (models) tasks are parallelizable.
  - Phase 4 (backend routes/controllers) tasks are parallelizable.
  - Phase 5 (frontend pages/components) tasks are parallelizable.
  - Give each task a unique taskId: "phaseName-N".
  - Keep task count 15-25 for a typical CRUD app.
  - File paths must be relative and must NOT start with "/".
  - Use "backend/src/..." and "frontend/src/..." paths.

  SCAFFOLD FILES ALREADY EXIST — NEVER CREATE OR EDIT THESE:
  - backend/src/config/db.js
  - backend/src/middleware/auth.js
  - backend/src/index.js
  - frontend/index.html
  - frontend/src/main.jsx
  - frontend/src/App.jsx
  - frontend/src/index.css
  - frontend/tailwind.config.js
  - frontend/postcss.config.js
  - frontend/vite.config.js
  - frontend/src/utils/api.js
  - .gitignore
  - all .env files
  - package.json files

  PHASE-SPECIFIC RULES:
  - Phase 1 "setup": create only app-specific helpers/context/constants. Do NOT create generic scaffold/config files.
  - Phase 2 "models": create database model/schema files only.
  - Phase 3 "middleware": create only app-specific validators, error helpers, or authorization helpers not already scaffolded.
  - Phase 4 "backend": create route/controller files. Do NOT create backend/src/index.js; routes are auto-wired later.
  - Phase 5 "frontend": create page/component files. Do NOT create frontend/src/App.jsx; pages are auto-wired later.
  - Phase 6 "integration": create only feature-level integration files if needed, such as shared layouts, auth context wiring, or frontend utility helpers. Do NOT create entrypoint files.
  - Phase 7 "documentation": include ONLY README.md.

  AUTO-GENERATED OUTSIDE THE PLAN:
  - backend/src/index.js route imports/mounts are auto-assembled.
  - frontend/src/App.jsx page imports/routes are auto-assembled.
  - Dockerfile, docker-compose.yml, nginx.conf, and deployment files are auto-generated by deploymentVerifier after coding is complete.

  ENTITY FILE NAMING RULES:
  - Backend models MUST use the file name from entity.modelFile.
    Example: entity.modelFile = "todoItem" -> "backend/src/models/todoItem.js"
  - Backend routes MUST use the file name from entity.routeFile.
    Example: entity.routeFile = "todoItemRoutes" -> "backend/src/routes/todoItemRoutes.js"

  QUALITY RULES:
  - Do not duplicate scaffold functionality.
  - Do not plan placeholder files.
  - Do not include TODO-only tasks.
  - Every task must produce useful runnable code or documentation.
  - Acceptance criteria must be concrete and testable.`;


function summarizeBlueprint(blueprint) {

  const dbSchema = blueprint.dbSchema || {};
  const dependencies = blueprint.dependencies || {};

  return {
    databaseType: dbSchema.databaseType,

    entities: summarizeEntities(blueprint.entities),
    tables: summarizeTables(dbSchema.tables),

    apiEndpoints: summarizeApiEndpoints(blueprint.apiEndpoints),
    frontendPages: summarizeFrontendPages(blueprint.frontendPages),
    folderStructure: blueprint.folderStructure,

    backendDeps: getDependencyNames(dependencies.backend),
    frontendDeps: getDependencyNames(dependencies.frontend),
  };
}

function summarizeEntities(entities = []) {
  return entities.map((entity) => ({
    name: entity.name,
    tableName: entity.tableName,
    apiPath: entity.apiPath,
    modelFile: entity.modelFile,
    routeFile: entity.routeFile,
  }));
}

function summarizeTables(tables = []) {
  return tables.map((table) => ({
    name: table.name,
    fieldCount: table.fields?.length || 0,
    foreignKeys: table.foreignKeys?.map((fk) => fk.references) || [],
  }));
}

function summarizeApiEndpoints(apiEndpoints = []) {
  return apiEndpoints.map((endpoint) => ({
    method: endpoint.method,
    path: endpoint.path,
    relatedTable: endpoint.relatedTable,
    requiresAuth: Boolean(endpoint.requiresAuth),
  }));
}

function summarizeFrontendPages(frontendPages = []) {
  return frontendPages.map((page) => ({
    name: page.name,
    route: page.route,
    componentCount: page.components?.length || 0,
  }));
}

function getDependencyNames(packageSection = {}) {
  return Object.keys(packageSection.dependencies || {});
}


export async function plannerAgentNode(state) {

  console.log("\n [Planner Agent] Creating build plan...\n");

  const { blueprint, clarifiedSpec } = state;

  const blueprintSummary = summarizeBlueprint(blueprint);

  const result = await safeCallGemini({
    systemPrompt: PLANNER_PROMPT,
    userPrompt: `This is the app name: ${clarifiedSpec.appName}\n\nThis is the blueprint summary:\n${JSON.stringify(blueprintSummary, null, 2)}\n\nUse this project specification as the source of truth:\n${JSON.stringify(clarifiedSpec, null, 2)}`,
    agentName: "plannerAgent",
  });


  if (!result.ok) {
    return { error: `plannerAgent failed: ${result.error}` };
  }

  const plan = result.parsed;

  return {
    taskQueue: plan,
    currentPhaseIndex: 0,
    currentTaskIndex: 0,
  };
}
